(()=>{'use strict';
const KEY='NOMAD_LIFE_STATE_V1';
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const state=()=>({world:document.getElementById('worldName')?.textContent||'NOMAD TERRE',money:document.getElementById('money')?.textContent||'🪙 1 000 000',avatar:document.getElementById('simName')?.textContent||'Mon Nomade',inventory:window.__nomadInventory||[],lastSeen:Date.now(),habitants:window.NOMAD_HABITANTS||[]});
function save(){try{localStorage.setItem(KEY,JSON.stringify(state()));setMsg('État NOMAD enregistré.')}catch(e){setMsg('Sauvegarde locale indisponible.')}}
function setMsg(t){const p=document.getElementById('theoMessage');if(p)p.textContent=t}
function restore(){try{const s=JSON.parse(localStorage.getItem(KEY)||'null');if(!s)return null;const n=(Date.now()-Number(s.lastSeen||Date.now()));return {...s,elapsed:n}}catch(e){return null}}
const old=restore();
const css=`#theoBtn{position:absolute;z-index:12;left:12px;bottom:12px;background:#17252bf2;color:#fff;border:1px solid #ffffff22;border-radius:16px;padding:10px 13px;box-shadow:0 6px 22px #0005;font-weight:800}#theoPanel{position:absolute;z-index:20;right:12px;top:74px;width:min(390px,calc(100vw - 24px));max-height:72vh;overflow:auto;background:#17252bf5;color:#fff;border:1px solid #ffffff1c;border-radius:22px;padding:15px;box-shadow:0 14px 45px #0006;backdrop-filter:blur(14px);display:none}#theoPanel.open{display:block}.theoHead{display:flex;justify-content:space-between;align-items:center}.theoHead b{font-size:18px}.theoClose{min-height:34px;padding:5px 9px;background:#ffffff12;color:#fff}.theoIntro{font-size:11px;opacity:.75;margin:7px 0 12px}.theoGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.theoCard{background:#ffffff0b;border:1px solid #ffffff12;border-radius:13px;padding:9px}.theoCard b{display:block;font-size:11px}.theoCard span{font-size:10px;opacity:.78}.theoOk{color:#9fe3ae}.theoInfo{margin-top:9px;padding:10px;border-radius:13px;background:#ffffff0b;font-size:10px;line-height:1.45}.theoActions{display:flex;gap:7px;margin-top:10px}.theoActions button{flex:1;background:#fff;color:#17252b;font-size:11px}.theoActions .secondary{background:#ffffff12;color:#fff}.theoMemory{margin-top:10px;font-size:9px;opacity:.65}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const btn=document.createElement('button');btn.id='theoBtn';btn.textContent='🧠 T.H.E.O.';document.getElementById('game')?.appendChild(btn);
const panel=document.createElement('section');panel.id='theoPanel';panel.innerHTML=`<div class="theoHead"><b>🧠 T.H.E.O.</b><button class="theoClose">✕</button></div><div class="theoIntro">Centre de coordination NOMAD · observation, mémoire, analyse et accompagnement.</div><div class="theoGrid"><div class="theoCard"><b>🌍 Monde</b><span id="theoWorld">NOMAD TERRE</span></div><div class="theoCard"><b>🕒 Simulation</b><span id="theoClock">08:00</span></div><div class="theoCard"><b>⚡ Énergie</b><span class="theoOk">● Nominale</span></div><div class="theoCard"><b>💧 Ressources</b><span class="theoOk">● Nominales</span></div><div class="theoCard"><b>📡 Communications</b><span class="theoOk">● Réseau actif</span></div><div class="theoCard"><b>🛰️ Infrastructures</b><span class="theoOk">● Surveillance active</span></div></div><div class="theoInfo" id="theoMessage">T.H.E.O. est prêt. Le monde peut continuer à évoluer pendant ton absence.</div><div class="theoInfo" id="theoHabitants">👥 Habitants : analyse en attente…</div><div class="theoActions"><button id="theoSave">💾 Enregistrer</button><button id="theoClose2" class="secondary">Fermer</button></div><div class="theoMemory" id="theoMemory">Mémoire locale NOMAD : active</div>`;document.getElementById('game')?.appendChild(panel);
function refresh(){const w=document.getElementById('worldName')?.textContent||'NOMAD TERRE';document.getElementById('theoWorld').textContent=w;document.getElementById('theoClock').textContent=document.getElementById('clock')?.textContent||'08:00';const h=document.getElementById('theoHabitants');const a=window.NOMAD_HABITANTS||[];if(h)h.innerHTML=a.length?'👥 <b>Vie des habitants</b><br>'+a.map(x=>'• '+x.name+' — '+x.activity+'<br><small>Énergie '+x.energy+' · faim '+x.hunger+' · lien '+x.bond+'/100 · rencontres '+x.encounters+'</small>').join('<br>'):'👥 Habitants : aucune donnée disponible.'}
function open(){refresh();panel.classList.add('open')}
function close(){panel.classList.remove('open')}
btn.addEventListener('click',open);panel.querySelector('.theoClose').addEventListener('click',close);panel.querySelector('#theoClose2').addEventListener('click',close);panel.querySelector('#theoSave').addEventListener('click',save);
setInterval(()=>{refresh();if(document.getElementById('game')?.style.display!=='none')save()},30000);
window.addEventListener('beforeunload',save);
if(old){const days=Math.floor(old.elapsed/86400000);if(days>0){setTimeout(()=>{setMsg(`T.H.E.O. : tu étais absent depuis ${days} jour${days>1?'s':''}. Les habitants ont continué leur vie.`);const h=document.getElementById('theoHabitants');if(h)h.innerHTML+=''<br>🕒 Pendant ton absence, les routines NOMAD ont continué localement.'},700)}}
window.NOMAD_THEO={save,restore};
})();
